### ISSUE TITLE
Basic database.yml should be in repo and in mina shared folder

### ISSUE THREAD

**Issue by samnissen** [samnissen/polariscope_2#29]
``` yml
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: polariscope_two_dev
  pool: 5
  username: polariscope_two_dev
  password: polariscope_two_dev
  socket: <%= ENV['PSAAPPMYSQLSOCKETLOCATION'] %>
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: polariscope_two_test
  pool: 5
  username: polariscope_two_test
  password: polariscope_two_test
  socket: <%= ENV['PSAAPPMYSQLSOCKETLOCATION'] %>
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: polariscope_two
  pool: 5
  username: <%= ENV['PSAAPPMYSQLUSERNAME'] %>
  password: <%= ENV['PSAAPPMYSQLPASSWORD'] %>
  socket: <%= ENV['PSAAPPMYSQLSOCKETLOCATION'] %>
```
